#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'twoStacks' function below.
#
# The function is expected to return an INTEGER.
# The function accepts following parameters:
#  1. INTEGER maxSum
#  2. INTEGER_ARRAY a
#  3. INTEGER_ARRAY b
#

def twoStacks(maxSum, a, b):
    count = 0
    sum_val = 0
    i = 0
    j = 0
    while i < len(a) and sum_val + a[i] <= maxSum:
        sum_val += a[i]
        i += 1
    count = i
    while j < len(b) and i >= 0:
        sum_val += b[j]
        j += 1
        while sum_val > maxSum and i > 0:
            i -= 1
            sum_val -= a[i]

        if sum_val <= maxSum and (i + j) > count:
            count = i + j

    return count

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    g = int(input().strip())

    for g_itr in range(g):
        first_multiple_input = input().rstrip().split()

        n = int(first_multiple_input[0])

        m = int(first_multiple_input[1])

        maxSum = int(first_multiple_input[2])

        a = list(map(int, input().rstrip().split()))

        b = list(map(int, input().rstrip().split()))

        result = twoStacks(maxSum, a, b)

        fptr.write(str(result) + '\n')

    fptr.close()
