#!/bin/python3

import math
import os
import random
import re
import sys


def saveThePrisoner(n, m, s):
    warn = (s+m-1)%n
    return warn if warn!=0 else n
    t=int(input())
    for _ in range(t):
        n,m,s = map(int, input().split())
        print(saveThePrisoner(n, m, s))
        

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    t = int(input().strip())

    for t_itr in range(t):
        first_multiple_input = input().rstrip().split()

        n = int(first_multiple_input[0])

        m = int(first_multiple_input[1])

        s = int(first_multiple_input[2])

        result = saveThePrisoner(n, m, s)

        fptr.write(str(result) + '\n')

    fptr.close()
